server:
  host: "localhost"
  listen_port: "8080"

resources:
  - name: Server1
    endpoint: /Server1
    destination_url: "http://localhost:9001"
  - name: Server2
    endpoint: /Server2
    destination_url: "http://localhost:9002"
  - name: Server3
    endpoint: /Server3
    destination_url: "http://localhost:9003"